---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gyu5la0fbzjq/public_html/panel.casaglick.com/

    - /bin/mkdir -p $DEPLOYPATH

    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp *.js $DEPLOYPATH
    - /bin/cp *.css $DEPLOYPATH

    - /bin/rm -rf ${DEPLOYPATH}/assets
    - /bin/cp -R assets $DEPLOYPATH
